name: servantauth
version: 0.1.0.0
github: "githubuser/servantauth"
license: BSD3
author: "Ulrich Schuster"
maintainer: "ulrich.schuster@koing.de"
copyright: "2021 Ulrich Schuster"

extra-source-files:
  - README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/servantauth#readme>

dependencies:
  - base
  - rio
  - aeson
  - servant-server
  - servant-auth
  - servant-auth-server
  - wai
  - warp
  - mtl
  - tagged
  - http-types
  - bytestring

ghc-options:
  # Recommended options from https://github.com/commercialhaskell/rio#monads
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wpartial-fields
  - -Wredundant-constraints
  - -fwarn-tabs

library:
  source-dirs: src

executables:
  servantauth-exe:
    main: Main.hs
    source-dirs: app
    dependencies:
      - servantauth
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

tests:
  servantauth-test:
    main: Test.hs
    source-dirs:
      - test
      - src
    dependencies:
      - tasty
      - tasty-hunit
      - tasty-hspec
      - tasty-quickcheck
      - tasty-discover
      - QuickCheck
      - quickcheck-instances
      - quickcheck-text
      - checkers
      - hspec
